<?php

namespace examBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * examRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class examRepository extends EntityRepository
{
}
