exam_index:
    path:     /
    defaults: { _controller: "examBundle:exam:index" }
    methods:  GET

exam_show:
    path:     /{id}/show
    defaults: { _controller: "examBundle:exam:show" }
    methods:  GET

exam_new:
    path:     /new
    defaults: { _controller: "examBundle:exam:new" }
    methods:  [GET, POST]

exam_edit:
    path:     /{id}/edit
    defaults: { _controller: "examBundle:exam:edit" }
    methods:  [GET, POST]

exam_delete:
    path:     /{id}/delete
    defaults: { _controller: "examBundle:exam:delete" }
    methods:  DELETE
